//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTradingHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerFeedback
    {
        public int Id { get; set; }
        public string Feekback { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
    }
}
