//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTradingHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.BuyerRequests = new HashSet<BuyerRequest>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Grade { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Color { get; set; }
        public string Image { get; set; }
        public Nullable<int> AvailableQuantity { get; set; }
        public Nullable<int> RequiredDeliveryDays { get; set; }
        public bool IsHomePageDisplay { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public System.DateTime Date { get; set; }
        public int Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerRequest> BuyerRequests { get; set; }
        public virtual User User { get; set; }
    }
}
